### PR TITLE
Make `@KomapperProjection` independent from `@KomapperEntity`

### PR DESCRIPTION
**Pull request by nakamura-to**
The class annotated with `@KomapperProjection` no longer needs to have `@KomapperId`.

**Entity and Projection**
```kotlin
@KomapperEntity
data class Person(@KomapperId val id:Int, val firstName: String, val lastName: String, val age: Int)

@KomapperProjection
data class PersonDto(val name: String, val age: Int)
```

**Query**
```kotlin
val p = Meta.person
val query: Query<List<PersonDto>> = QueryDsl.from(p)
  .selectAsPersonDto(
    name = concat(concat(p.fristName, " "), p.lastName), 
    age = p.age,
  )
```

### CODE REVIEW

**Comment by dave08** [comment]
Looks great :smile: ! So this doesn't generate the extension on Meta unless annotated with `@KomapperEntity` too?

The only thing that would have been great is to take into consideration properties with default values or nullables and allow that to be used as default values in generated selectAsXXX functions, since that would allow re-use of certain projections when missing certain info to fill it in the query... I'm not sure how complicated that would be know that you seperated the projection generation from the entity generation...

Thanks for this PR!

**Comment by nakamura-to** [comment]
Thank you for your comment.

> So this doesn't generate the extension on Meta unless annotated with @KomapperEntity too?

No, it doesn't generate the extension on `Meta`.
However it generate the extension on `ProjectionMeta`.

> The only thing that would have been great is to take into consideration properties with default values or nullables and allow that to be used as default values in generated selectAsXXX functions

Speaking of default values, it's not possible because KSP doesn't support it.
https://github.com/google/ksp/issues/642

What kind of support are you looking for regarding nullables?

**Comment by dave08** [comment]
Say I have:
```kotlin
@KomapperProjection
data class Foo(val bar: Int, val baz: String? = null, val baz2: String = "some value")

// Can this be generated? (I didn't write the types right, I know, it should be 
fun ....selectAsFoo(bar: ColumnExpression<Int, Int>, baz: ColumnExpression<String, String>? = null, baz2: ColumnExpression<String, String>?  = null)
// If null is passed to any parameter or a parameter is not provided, then you can instantiate Foo with the default values. Ksp doesn't need to get the default values, you just need to be able to instantiate the class with them if they are not provided...
```

**Comment by nakamura-to** [comment]
To decide whether to use default values for each instance, it is necessary to retrieve the default values in KSP. However, this is impossible to achieve as KSP does not support it. This discussion was carried out at 
https://slack-chats.kotlinlang.org/t/16292178/why-is-a-komapperprojection-a-komapperentity-it-s-a-bit-conf#2639bf4d-50cc-4588-ab13-9edd029bde09

**Comment by nakamura-to** [comment]
I have added two utility functions.

- tranform
- nullLiteral

```kotlin
@KomapperEntity
data class Address(@KomapperId val id:Int, val street: String, val version: Int)

@KomapperProjection
data class AddressDto(val street: String?, val comment = String)
```

``` kotlin
val a = Meta.address
val query: Query<AddressDto> = QueryDsl.from(a)
  .selectAsAddressDto(
    street = nullLiteral(), // set a null to the street property of AddressDto
    comment = a.id.transform { "Comment for id: $it" }, // transform an id value to a string value
  ).single()
val dto = db.runQuery(query)
println(dto.street) // null
println(dto.comment) // Comment for id: 1
```

**Comment by nakamura-to** [comment]
No, they will not default to null. I believe that in many cases, just because a field is nullable does not mean we would want its default value to be null.

**Pull request merged**
