### PR TITLE
Throws an understandable exception when a bind variable is not found in Template Queries

### PR DESCRIPTION
**Pull request by nakamura-to**
```kotlin
db.runQuery {
    val sql = "select * from address where street = /*street*/'test'"
    QueryDsl.fromTemplate(sql)
        .bind("unknown", "STREET 10")
        .select(asAddress)
}
```

The above code throws an exception with a stack trace like this:

```
org.komapper.template.sql.SqlException: The expression evaluation was failed at <select * from address where street = /*street*/'test'>:1:47.
...
Caused by: org.komapper.template.expression.ExprException: The variable "street" is not found. Make sure the variable name is correct. <street>:6
```

### CODE REVIEW

**Comment by dave08** [comment]
Maybe there should also be a mention that the `unknown` bind parameter doesn't exist? And is `variable` something that a user would understand right away? Maybe "template variable" might be a bit more specific?

**Comment by dave08** [comment]
Much better, thanks! No mention of "unknown" not binding to anything, though... it wouldn't make any errors in the actual results, but rather might leave some unecessary bindings in the codebase when refactoring. I'm not sure if it should crash, but maybe have some kind of log on this situation?

**Comment by nakamura-to** [comment]
> Maybe there should also be a mention that the unknown bind parameter doesn't exist?

It isn't easy to detect parameters that are not referenced in the template. Besides, doing so has performance drawbacks.

>  And is variable something that a user would understand right away? Maybe "template variable" might be a bit more specific?

Thanks for the suggestion. I have changed the message to be more accurate.

**Comment by nakamura-to** [comment]
> but maybe have some kind of log on this situation?

That is a good idea. However, I will treat it as a separate issue.

**Pull request merged**
