### PR TITLE
Add updatable attribute to @KomapperColumn

### PR DESCRIPTION
**Pull request by GreyTeardrop**
Add new `updatable` flag to the `@KomapperColumn` annotation. Columns are updatable by default; if `updatable` is set to `false`, the column is excluded from generated update statements similar to `idProperties()` and `createdAtProperty()`.

**Background**. The primary intended use case is the implementation of auditing fields, specifically the "created by" field that should behave similarly to the "created at" field already supported by Komapper.

Additional context: https://github.com/komapper/komapper/discussions/1396.

TODOs:
- [x] KDocs
- [x] Tests

### CODE REVIEW

**Comment by nakamura-to** [comment]
Thank you very much.
This is an excellent improvement!

**Comment by GreyTeardrop** [comment]
@nakamura-to Thank you for merging this change! If you want to, I can also add a note about this feature in the `komapper-docs` repo (although I can only cover English language).

**Comment by nakamura-to** [comment]
@GreyTeardrop Thank you for the offer! Yes, we would appreciate it if you could add a note about this feature in the Komapper docs. Your help with the English documentation is invaluable.

Please refer to the following page for guidance on writing documentation: https://github.com/komapper/komapper-docs/blob/main/CONTRIBUTING.md

**Comment by GreyTeardrop** [comment]
I've added a small note about this feature in https://github.com/komapper/komapper-docs/pull/32; can later work on adding a few usages to `komapper-examples` repo.

**Pull request merged**
