### PR TITLE
Add the experimental association API

### PR DESCRIPTION
**Pull request by nakamura-to**
The KomapperAssociation annotation simplifies EntityStore operations.

Entity definitions:

```kotlin
@KomapperEntity
@KomapperAssociation(AssociationType.ONE_TO_MANY, Employee::class, "employees")
data class Department(
    @KomapperId
    @KomapperColumn("department_id")
    val departmentId: Int,
    @KomapperColumn("department_name")
    val departmentName: String,
)

@KomapperEntity(["employee", "manager"])
@KomapperAssociation(AssociationType.MANY_TO_ONE, Department::class)
@KomapperAssociation(AssociationType.ONE_TO_ONE, Address::class)
data class Employee(
    @KomapperId
    @KomapperColumn("employee_id")
    val employeeId: Int,
    @KomapperColumn("employee_name")
    val employeeName: String,
    @KomapperColumn("department_id")
    val departmentId: Int,
    @KomapperColumn("address_id")
    val addressId: Int,
)

@KomapperEntity
data class Address(
    @KomapperId
    @KomapperColumn(name = "address_id")
    val addressId: Int,
    val street: String,
)
```

The Komapper KSP processor generates the following code from the above entity definitions:

```kotlin
fun integration.core.Department.`employees`(store: org.komapper.core.dsl.query.EntityStore,thisSide: _Department,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Employee, *, *>,): Set<integration.core.Employee> {
    return store.oneToMany(thisSide, thatSide)[this] ?: emptySet()
}
fun integration.core.Employee.`department`(store: org.komapper.core.dsl.query.EntityStore,thisSide: _Employee,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Department, *, *>,): integration.core.Department? {
    return store.oneToMany(thatSide, thisSide).asSequence().firstOrNull { it.value.contains(this) }?.key
}
fun integration.core.Employee.`address`(store: org.komapper.core.dsl.query.EntityStore,thisSide: _Employee,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Address, *, *>,): integration.core.Address? {
    return store.oneToOne(thisSide, thatSide)[this]
}
```

With these generated codes you can write as followings:

```kotlin
val d = Meta.department
val e = Meta.employee
val a = Meta.address

// get an EntityStore
val store = db.runQuery {
    QueryDsl.from(d)
        .innerJoin(e) {
            d.departmentId eq e.departmentId
        }.innerJoin(a) {
            e.addressId eq a.addressId
        }.includeAll()
}

// operate the EntityStore
for (department in store[d]) {
    // use the generated extension function
    val employees = department.employees(store, d, e)
    for (employee in employees) {
        // use the generated extension function
        val address = employee.address(store, e, a)
        println("department=${department.departmentName}, employee=${employee.employeeName}, address=${address?.street}")
    }
}
```

In the future, the generated code will use the context receiver:

```kotlin
context(EntityStoreContext)
fun integration.core.Department.`employees`(thisSide: _Department,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Employee, *, *>,): Set<integration.core.Employee> {
    return store.oneToMany(thisSide, thatSide)[this] ?: emptySet()
}
context(EntityStoreContext)
fun integration.core.Employee.`department`(thisSide: _Employee,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Department, *, *>,): integration.core.Department? {
    return store.oneToMany(thatSide, thisSide).asSequence().firstOrNull { it.value.contains(this) }?.key
}
context(EntityStoreContext)
fun integration.core.Employee.`address`(thisSide: _Employee,thatSide: org.komapper.core.dsl.metamodel.EntityMetamodel<integration.core.Address, *, *>,): integration.core.Address? {
    return store.oneToOne(thisSide, thatSide)[this]
}
```

### CODE REVIEW

**Comment by nakamura-to** [comment]
We have made our API simpler:

Entity definitions:
```kotlin
@KomapperEntity
@KomapperOneToMany(Employee::class, navigator = "employees")
data class Department(
    @KomapperId
    @KomapperColumn("department_id")
    val departmentId: Int,
    @KomapperColumn("department_name")
    val departmentName: String,
)

@KomapperEntity(["employee", "manager"])
@KomapperManyToOne(Department::class)
@KomapperOneToOne(Address::class)
data class Employee(
    @KomapperId
    @KomapperColumn("employee_id")
    val employeeId: Int,
    @KomapperColumn("employee_name")
    val employeeName: String,
    @KomapperColumn("department_id")
    val departmentId: Int,
    @KomapperColumn("address_id")
    val addressId: Int,
)

@KomapperEntity
data class Address(
    @KomapperId
    @KomapperColumn(name = "address_id")
    val addressId: Int,
    val street: String,
)
```

generated extension functions:
```kotlin
fun integration.core.Department.`employees`(
    store: org.komapper.core.dsl.query.EntityStore,
    source: integration.core._Department = org.komapper.core.dsl.Meta.`department`,
    target: integration.core._Employee = org.komapper.core.dsl.Meta.`employee`,
    ): Set<integration.core.Employee> {
    return store.oneToMany(source, target)[this] ?: emptySet()
}
fun integration.core.Employee.`address`(
    store: org.komapper.core.dsl.query.EntityStore,
    source: integration.core._Employee = org.komapper.core.dsl.Meta.`employee`,
    target: integration.core._Address = org.komapper.core.dsl.Meta.`address`,
    ): integration.core.Address? {
    return store.oneToOne(source, target)[this]
}
fun integration.core.Employee.`department`(
    store: org.komapper.core.dsl.query.EntityStore,
    source: integration.core._Employee = org.komapper.core.dsl.Meta.`employee`,
    target: integration.core._Department = org.komapper.core.dsl.Meta.`department`,
    ): integration.core.Department? {
    return store.manyToOne(source, target)[this]
}
```

application sample code:
```kotlin
val d = Meta.department
val e = Meta.employee
val a = Meta.address

// get an EntityStore
val store = db.runQuery {
    QueryDsl.from(d)
        .innerJoin(e) {
            d.departmentId eq e.departmentId
        }.innerJoin(a) {
            e.addressId eq a.addressId
        }.includeAll()
}

// operate the EntityStore
for (department in store[d]) {
    // use the generated extension function
    val employees = department.employees(store)
    for (employee in employees) {
       // use the generated extension function
        val address = employee.address(store)
        println("department=${department.departmentName}, employee=${employee.employeeName}, address=${address?.street}")
    }
}
```

**Comment by nakamura-to** [comment]
You can add the following code to build.gradle.kts to make it simple your code:
```kotlin
ksp {
    arg("komapper.enableEntityStoreContext", "true")
}
```

application sample code:
```kotlin
val d = Meta.department
val e = Meta.employee
val a = Meta.address

val store = database.runQuery {
    QueryDsl.from(d)
        .innerJoin(e) {
            d.departmentId eq e.departmentId
        }.innerJoin(a) {
            e.addressId eq a.addressId
        }.includeAll()
}

with(store.asContext()) {
    for (department in store[d]) {
        val employees = department.employees() // you don't need to pass any arguments
        for (employee in employees) {
            val address = employee.address() // you don't need to pass any arguments
            println("department=${department.departmentName}, employee=${employee.employeeName}, address=${address?.street}")
        }
    }
}
```

**Comment by dave08** [comment]
This seems MUCH nicer :smiley:! One little detail, maybe for consistency... the `store[d]` could maybe be replaced by `store.departments`...? Since `Department` is the aggregate root (it has all the relational annotations on it...), it could "come directly from"  the store... and other object "come from" it.

**Comment by dave08** [comment]
Although, I'd mark all this new api as experimental... since these kinds of things might change as they are used... and new ideas might pop up.

**Comment by nakamura-to** [comment]
> the store[d] could maybe be replaced by store.departments...? 

That's an interesting idea. How about introducing an annotation called KomapperAggregateRoot?

```kotlin
@KomapperEntity
@KomapperAggregateRoot(navigator = "departments")
@KomapperOneToMany(Employee::class, navigator = "employees")
data class Department( ... )
```

The following code is generated from KomapperAggregateRoot:

```kotlin
fun EntityStore.departments(target: _Department = Meta.department) : List<Department> {
    return this[target]
}
```

> I'd mark all this new api as experimental

I agree with you. I am considering including this feature in the next release, but it should be experimental.

**Comment by dave08** [comment]
> How about introducing an annotation called KomapperAggregateRoot?

Yeah, that could do it! The only thing is that if only one aggregate root object is requested, maybe there should be a seperate generated function to retreive it?

**Comment by nakamura-to** [comment]
Does that mean you want the following function?

```kotlin
fun EntityStore.departments(target: _Department = Meta.department) : Department {
    return this[target].first()
}
```

It is possible, but rather than generating code, the users might write the following themselves:

```kotlin
val department = store.departments().single()
```

**Comment by dave08** [comment]
> It is possible, but rather than generating code, the users might write the following themselves:

I'm wondering if in the future, this might help if the EntityStore was refactored to cache it's contents and then when 
 a single aggregate root is requested, it could store/return it as an object instead of having to create a useless list for it...

**Pull request merged**
