### PR TITLE
Reimplement the SQL Partial feature

### PR DESCRIPTION
**Pull request by nakamura-to**
This pull request enables the KomapperPartial annotation for classes and allows them to be used as command parameters.

### Basic example

```kotlin
@KomapperPartial(
    """
    limit /* limit */0 offset /* offset */0
    """,
)
data class Pagination(val limit: Int, val offset: Int)

@KomapperCommand(
    """
    select * from address order by address_id
    /*> pagination */
    """,
)
class UsePartial(val pagination: Pagination?) : Many<Address>({ selectAsAddress() })
```

When the `pagination` parameter is non-null, the following SQL is generated:

```sql
select * from address order by address_id limit ? offset ?
```

When the `pagination` parameter is null, the following SQL is generated:

```sql
select * from address order by address_id
```

### Advanced example: polymorphic partial

You can also use sealed interfaces and sealed classes to utilize SQL Partial polymorphically.
```kotlin
sealed interface FilterBy {
    @KomapperPartial(
        """
        where street = /* street */''
        """,
    )
    class Street(val street: String) : FilterBy

    @KomapperPartial(
        """
        where address_id = /* id */0
        """,
    )
    class Id(val id: Int) : FilterBy
}

@KomapperCommand(
    """
    select * from address
    /*> filterBy */
    """,
)
class UseSealedPartial(val filterBy: FilterBy?) : Many<Address>({ selectAsAddress() })
```

When an instance of `FilterBy.Street` is used as a command argument, the following SQL is generated:

```sql
select * from address where street = ?
```

Similarly, when an instance of `FilterBy.Id` is used as a command argument, the following SQL is generated:

```sql
select * from address where address_id = ?
```

### CODE REVIEW

**Comment by dave08** [comment]
This is great :+1:, thanks! Three points I'm wondering though:

1) Now that the partial annotation is on CLASS, I'd suppose it's not possible to use `const val`s anymore. That in itself isn't a big deal, but what if one wants to have a parameterless Partial? It would be a bit of a waste to create a class with an empty constructor and create an instance of it any time it's needed... So I'm suggesting:

```kotlin
@KomapperPartial(...)
object FooPartial

@KomapperCommand("""
...
/*> FooPartial */
""")
class Baz(val id: Int) // No reference to FooPartial here... but in the template use the object name
```

2) If one want to provide alternative parameterless partials:
```kotlin
sealed interface FooCriteria

@KomapperPartial(...)
object FooPartial1 : FooCriteria

@KomapperPartial(...)
object FooPartial2 : FooCriteria

@KomapperCommand("""
...
/*> criteria */
""")
class Baz(val id: Int, val criteria: FooCriteria) // Just pass the object reference wanted here... in the template, use the parameter name.
```

3) It doesn't seem like this is tested:

```kotlin
sealed interface Criteria {
   sealed interface ByDate : Criteria
   
   // not nested in ByDate, but derives from it...
   @KomapperPartial(...)
   data class Created(val ...) : ByDate
}
```
We use this form to limit the criteria type passed to the query to be only by date, but we don't want to have to write: `Criteria.ByDate.Created(...)`,  in this case it might be clearer the long form, but in others, it's just unnecessary...

Thanks a lot again for this feature, it'll make it SO much nicer to use commands in our current project :smiley:!

**Comment by nakamura-to** [comment]
@dave08  Thank you for your feedback.
Everything you suggested is already supported in this PR.

However, to reference a class from an SQL template, you need to use the `@binary name@` notation:

```kotlin
package example

@KomapperPartial(...)
object FooPartial

@KomapperCommand("""
...
/*> @example.FooPartial@ */
""")
class Baz(val id: Int)
```

If `FooPartial` is an inner class of the `example.Foo` class, you would write it as `@example.Foo$FooPartial@`.

The binary name notation is prone to errors, so personally, I think it’s better to use default arguments and reference them by parameter name:

```kotlin
package example

@KomapperPartial(...)
object FooPartial

@KomapperCommand("""
...
/*> partial */
""")
class Baz(val id: Int, val partial: FooPartial = FooPartial)
```

**Comment by dave08** [comment]
> Everything you suggested is already supported in this PR.

Wow, that's great!

And yeah, I do agree the binary name format isn't too nice... but if the partial is in the same `package` does it have to include the package anyways? If not, that might still be an option to not have such a messy path... also maybe a typealias in the same file could be used to simplify that binary name?

This is not really critical, just maybe a "nice touch" to decouple the package structure from commands in such a case. The main features are already great and largely sufficient!

**Comment by nakamura-to** [comment]
Thanks for your feedback.

Since excluding the package name from the binary name isn’t a critical feature, we’ve decided not to include it in the next release.

**Pull request merged**
